using Tyuiu.ZolotovaKA.Sprint5.Task0.V10.Lib;

DataService ds = new DataService();
Console.Title = "Спринт #5 | Выполнила: Золотова К. А. | ИСПб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #5                                                               *");
Console.WriteLine("* Тема:  Класс File. Запись данных в текстовый файл                       *");
Console.WriteLine("* Задание #0                                                              *");
Console.WriteLine("* Вариант #10                                                             *");
Console.WriteLine("* Выполнила: Золотова К. А. | ИСПб-24-1                                   *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Дано выражение F(x) = 1.6x^3-2.1x^2+7*x, вычислить его значение при     *");
Console.WriteLine("* x = 2, результат сохранить в текстовый файл OutPutFileTask0.txt и       *");
Console.WriteLine("* вывести на консоль. Округлить до трёх знаков после запятой.             *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");
int x = 2;
Console.WriteLine("x = " + x);
Console.WriteLine("***************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                              *");
Console.WriteLine("***************************************************************************");
string res = ds.SaveToFileTextData(x);
Console.WriteLine("Файл: " + res);
Console.WriteLine("Создан!");
Console.ReadKey();